### ISSUE TITLE
Inaccurate README?

### ISSUE THREAD

**Issue by stephencelis** [carlosparamio/rack-facebook#1]
The README says:

```
use Rack::Facebook, "my_facebook_secret_key"
```

The documentation says:

```
use Rack::Facebook, :application_secret => "SECRET", :api_key => "APIKEY"
```

It appears the documentation is right, so shouldn't the README get updated?

It would also be a slightly simpler API (and match Rack::OAuth), to just specify `:secret` and `:key` (although verboseness has its charm).

**Comment by carlosparamio** [comment]
Thank you for pointing this documentation bug!

I like your suggestion about the changes to the API. It definitively deserves a slight change, specially to unify the name of the parameters used on the Rack configuration with the name of the environment keys used to store the final values. But I don't want to break the compatibility (yet).
